server:
  port: 8081

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://fd-postgres-users:5432/user_service
    username: fd_user
    password: fd_password
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
