server:
  port: 8081

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/user_service
    username: fd_user
    password: fd_password
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

keycloak:
  auth-server-url: http://localhost:9990
  realm: food-delivery
  client-id: food-delivery-gateway
  client-secret: dummy-secret

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
